/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mist;

import javax.swing.JOptionPane;

/**
 *
 * @author Fenix
 */
public class JogoMisturando3 extends javax.swing.JFrame {

    /**
     * Creates new form JogoMistureba
     */
    public JogoMisturando3() {
        initComponents();
        mist.palavras();
        mist.resposta();
        txtCaixa.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblResp1 = new javax.swing.JLabel();
        lblResp2 = new javax.swing.JLabel();
        lblResp3 = new javax.swing.JLabel();
        lblResp4 = new javax.swing.JLabel();
        lblResp5 = new javax.swing.JLabel();
        txtCaixa = new javax.swing.JTextField();
        Limpar = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mistureba");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Dicas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Mamífero");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Adjetivo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Revista de Carro");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Doce");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Ator Brasileiro");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Resposta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 11, -1, -1));

        lblResp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResp1.setForeground(java.awt.Color.white);
        lblResp1.setText("E???????");
        jPanel1.add(lblResp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 50, -1, -1));

        lblResp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResp2.setForeground(new java.awt.Color(255, 255, 255));
        lblResp2.setText("I??????????");
        jPanel1.add(lblResp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 75, -1, -1));

        lblResp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResp3.setForeground(java.awt.Color.white);
        lblResp3.setText("Q?????R????");
        jPanel1.add(lblResp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 100, -1, -1));

        lblResp4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResp4.setForeground(java.awt.Color.white);
        lblResp4.setText("M???????");
        jPanel1.add(lblResp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 125, -1, -1));

        lblResp5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResp5.setForeground(java.awt.Color.white);
        lblResp5.setText("D?? S???????");
        jPanel1.add(lblResp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 150, -1, -1));
        jPanel1.add(txtCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 30));

        Limpar.setBackground(new java.awt.Color(255, 0, 0));
        Limpar.setForeground(new java.awt.Color(255, 255, 255));
        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jPanel1.add(Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        btn11.setBackground(new java.awt.Color(255, 255, 255));
        btn11.setText("EL");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 219, 82, 45));

        btn12.setBackground(new java.awt.Color(0, 0, 0));
        btn12.setForeground(new java.awt.Color(255, 255, 255));
        btn12.setText("NTE");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel1.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 219, 82, 45));

        btn13.setBackground(new java.awt.Color(255, 255, 255));
        btn13.setText("PAN");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        jPanel1.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 219, 82, 45));

        btn14.setBackground(new java.awt.Color(0, 0, 0));
        btn14.setForeground(new java.awt.Color(255, 255, 255));
        btn14.setText("DAN");
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        jPanel1.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 219, 82, 45));

        btn15.setBackground(new java.awt.Color(255, 255, 255));
        btn15.setText("INT");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        jPanel1.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 219, 82, 45));

        btn21.setBackground(new java.awt.Color(0, 0, 0));
        btn21.setForeground(new java.awt.Color(255, 255, 255));
        btn21.setText("STU");
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        jPanel1.add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 82, 45));

        btn22.setBackground(new java.awt.Color(255, 255, 255));
        btn22.setText("ZI");
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        jPanel1.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 275, 82, 45));

        btn23.setBackground(new java.awt.Color(0, 0, 0));
        btn23.setForeground(new java.awt.Color(255, 255, 255));
        btn23.setText("QU");
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });
        jPanel1.add(btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 275, 82, 45));

        btn24.setBackground(new java.awt.Color(255, 255, 255));
        btn24.setText("LBA");
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });
        jPanel1.add(btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 275, 82, 45));

        btn25.setBackground(new java.awt.Color(0, 0, 0));
        btn25.setForeground(new java.awt.Color(255, 255, 255));
        btn25.setText("RO");
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });
        jPanel1.add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 275, 82, 45));

        btn31.setBackground(new java.awt.Color(255, 255, 255));
        btn31.setText("AT");
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });
        jPanel1.add(btn31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 331, 82, 45));

        btn32.setBackground(new java.awt.Color(0, 0, 0));
        btn32.setForeground(new java.awt.Color(255, 255, 255));
        btn32.setText("AS");
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });
        jPanel1.add(btn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 331, 82, 45));

        btn33.setBackground(new java.awt.Color(255, 255, 255));
        btn33.setText("GE");
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });
        jPanel1.add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 331, 82, 45));

        btn34.setBackground(new java.awt.Color(0, 0, 0));
        btn34.setForeground(new java.awt.Color(255, 255, 255));
        btn34.setText("CH");
        btn34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn34ActionPerformed(evt);
            }
        });
        jPanel1.add(btn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 331, 82, 45));

        btn35.setBackground(new java.awt.Color(255, 255, 255));
        btn35.setText("ROD");
        btn35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn35ActionPerformed(evt);
            }
        });
        jPanel1.add(btn35, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 331, 82, 45));

        btn41.setBackground(new java.awt.Color(0, 0, 0));
        btn41.setForeground(new java.awt.Color(255, 255, 255));
        btn41.setText("ELI");
        btn41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn41ActionPerformed(evt);
            }
        });
        jPanel1.add(btn41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 387, 82, 45));

        btn42.setBackground(new java.awt.Color(255, 255, 255));
        btn42.setText("AN");
        btn42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn42ActionPerformed(evt);
            }
        });
        jPanel1.add(btn42, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 387, 82, 45));

        btn43.setBackground(new java.awt.Color(0, 0, 0));
        btn43.setForeground(new java.awt.Color(255, 255, 255));
        btn43.setText("TE");
        btn43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn43ActionPerformed(evt);
            }
        });
        jPanel1.add(btn43, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 387, 82, 45));

        btn44.setBackground(new java.awt.Color(255, 255, 255));
        btn44.setText("MAR");
        btn44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn44ActionPerformed(evt);
            }
        });
        jPanel1.add(btn44, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 387, 82, 45));

        btn45.setBackground(new java.awt.Color(0, 0, 0));
        btn45.setForeground(new java.awt.Color(255, 255, 255));
        btn45.setText("EF");
        btn45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn45ActionPerformed(evt);
            }
        });
        jPanel1.add(btn45, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 387, 82, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn45ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn45.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + (btn45.getText());
        btn45.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn45ActionPerformed

    private void btn44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn44ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn44.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn44.getText();
        btn44.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn44ActionPerformed

    private void btn43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn43ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn43.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn43.getText();
        for(int i=0; i < mist.palavras.length ; i++){
            if (mist.resposta[i].equals(mist.comparacao(resposta))) {
                lblResp1.setText(mist.comparacao(resposta));
                resposta = "";
                visualizacao = "";
                txtCaixa.setText("");
            }
        }
        btn43.setVisible(false);
        if(mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText()))
        {
            JOptionPane.showMessageDialog(null, "Parabéns, você terminou!");
            
            InicioMisturando inicio = new InicioMisturando();
            inicio.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn43ActionPerformed

    private void btn42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn42ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn42.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn42.getText();
        btn42.setVisible(false);


    }//GEN-LAST:event_btn42ActionPerformed

    private void btn41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn41ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn41.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn41.getText();
        btn41.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn41ActionPerformed

    private void btn35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn35ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn35.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn35.getText();

        btn35.setVisible(false);
        if(mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText()))
        {
            JOptionPane.showMessageDialog(null, "Parabéns, você terminou!");
            
            InicioMisturando inicio = new InicioMisturando();
            inicio.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btn35ActionPerformed

    private void btn34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn34ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn34.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn34.getText();
                for (int i = 0; i < 15; i++) {
            if (mist.resposta[i].equals(mist.comparacao(resposta))) {
                lblResp5.setText(mist.comparacao(resposta));
                resposta = "";
                visualizacao = "";
                txtCaixa.setText("");
            }
        }
        if(mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText())){
            JOptionPane.showMessageDialog(null, "Parabéns, você terminou!");
            
            InicioMisturando inicio = new InicioMisturando();
            inicio.setVisible(true);
            this.dispose();
        }
        btn34.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn34ActionPerformed

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn33.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn33.getText();
        btn33.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn33ActionPerformed

    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn32.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn32.getText();
        for(int i=0; i < mist.palavras.length ; i++){
            if (mist.resposta[i].equals(mist.comparacao(resposta))) {
                lblResp3.setText(mist.comparacao(resposta));
                resposta = "";
                visualizacao = "";
                txtCaixa.setText("");
            }
        }
        if(mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText()))
        {
            JOptionPane.showMessageDialog(null, "Parabéns, você terminou!");
            
            InicioMisturando inicio = new InicioMisturando();
            inicio.setVisible(true);
            this.dispose();
        }
        btn32.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn31.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn31.getText();
        btn31.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn31ActionPerformed

    private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn25.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn25.getText();
        btn25.setVisible(false);

    }//GEN-LAST:event_btn25ActionPerformed

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn24.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn24.getText();
        btn24.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn24ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn23.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn23.getText();

        btn23.setVisible(false);
        if(mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText()))
        {
            JOptionPane.showMessageDialog(null, "Parabéns, você terminou!");
            
            InicioMisturando inicio = new InicioMisturando();
            inicio.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn22.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn22.getText();
        btn22.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn21.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn21.getText();
        btn21.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn15.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn15.getText();;

        btn15.setVisible(false);
        if(mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText()))
        {
            JOptionPane.showMessageDialog(null, "Parabéns, você terminou!");
            
            InicioMisturando inicio = new InicioMisturando();
            inicio.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn14.getText());
        txtCaixa.setText(visualizacao);
        btn14.setVisible(false);
        resposta = resposta + btn14.getText();

        btn14.setVisible(false);
        mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText());
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn13.getText());
        txtCaixa.setText(visualizacao);
        btn13.setVisible(false);
        resposta = resposta + btn13.getText();
        for(int i=0; i < mist.palavras.length ; i++){
            if (mist.resposta[i].equals(mist.comparacao(resposta))) {
                lblResp4.setText(mist.comparacao(resposta));
                resposta = "";
                visualizacao = "";
                txtCaixa.setText("");
            }
        }
        if(mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText()))
        {
            JOptionPane.showMessageDialog(null, "Parabéns, você terminou!");
            
            InicioMisturando inicio = new InicioMisturando();
            inicio.setVisible(true);
            this.dispose();
        }
        btn13.setVisible(false);
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn12.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn12.getText();
       for(int i=0; i < mist.palavras.length ; i++){
            if (mist.resposta[i].equals(mist.comparacao(resposta))) {
                lblResp2.setText(mist.comparacao(resposta));
                resposta = "";
                visualizacao = "";
                txtCaixa.setText("");
            }
        }
        if(mist.fimDeJogo(lblResp1.getText(), lblResp2.getText(), lblResp3.getText(), lblResp4.getText(), lblResp5.getText()))
        {
                    JOptionPane.showMessageDialog(null, "Parabéns, você terminou!");
            
            InicioMisturando inicio = new InicioMisturando();
            inicio.setVisible(true);
            this.dispose();
        }
        btn12.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        visualizacao = visualizacao + mist.visualizacao(btn11.getText());
        txtCaixa.setText(visualizacao);

        resposta = resposta + btn11.getText();
        btn11.setVisible(false);
    }//GEN-LAST:event_btn11ActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed

        btn25.setVisible(mist.botaoLimpar(lblResp3.getText()));
        btn42.setVisible(mist.botaoLimpar(lblResp1.getText()));
        btn43.setVisible(mist.botaoLimpar(lblResp1.getText()));
        btn44.setVisible(mist.botaoLimpar(lblResp4.getText()));
        btn33.setVisible(mist.botaoLimpar(lblResp2.getText()));
        btn22.setVisible(mist.botaoLimpar(lblResp4.getText()));
        btn23.setVisible(mist.botaoLimpar(lblResp3.getText()));
        btn24.setVisible(mist.botaoLimpar(lblResp5.getText()));
        btn45.setVisible(mist.botaoLimpar(lblResp1.getText()));
        btn14.setVisible(mist.botaoLimpar(lblResp5.getText()));
        btn32.setVisible(mist.botaoLimpar(lblResp3.getText()));
        btn11.setVisible(mist.botaoLimpar(lblResp1.getText()));
        btn34.setVisible(mist.botaoLimpar(lblResp5.getText()));
        btn15.setVisible(mist.botaoLimpar(lblResp2.getText()));
        btn12.setVisible(mist.botaoLimpar(lblResp2.getText()));
        btn31.setVisible(mist.botaoLimpar(lblResp3.getText()));
        btn21.setVisible(mist.botaoLimpar(lblResp5.getText()));
        btn41.setVisible(mist.botaoLimpar(lblResp2.getText()));
        btn13.setVisible(mist.botaoLimpar(lblResp4.getText()));
        btn35.setVisible(mist.botaoLimpar(lblResp3.getText()));
        visualizacao = "";
        txtCaixa.setText("");
        resposta = "";
    }//GEN-LAST:event_LimparActionPerformed
    Misturando mist = new Misturando();
    String resposta = "";
    String visualizacao = "";

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpar;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResp1;
    private javax.swing.JLabel lblResp2;
    private javax.swing.JLabel lblResp3;
    private javax.swing.JLabel lblResp4;
    private javax.swing.JLabel lblResp5;
    private javax.swing.JTextField txtCaixa;
    // End of variables declaration//GEN-END:variables
}
